# Generated by Django 3.1.4 on 2021-02-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_details', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('connect_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=150)),
                ('connect_status', models.CharField(max_length=150, null=True)),
                ('connect_seek_rating', models.CharField(max_length=150, null=True)),
                ('connect_teach_rating', models.CharField(max_length=150, null=True)),
                ('connect_rate', models.CharField(max_length=150, null=True)),
                ('connect_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.class')),
            ],
        ),
        migrations.CreateModel(
            name='Connect_Message_Attach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_message_id', models.CharField(max_length=60)),
                ('connect_attach_file_blob', models.CharField(max_length=60, null=True)),
                ('connect_attach_file_type', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='connect_status',
            fields=[
                ('connect_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStat',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_details', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('ticket_desc', models.TextField(blank=True)),
                ('ticket_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('role', models.PositiveIntegerField(default=0)),
                ('seek_skills', models.CharField(max_length=150, null=True)),
                ('teach_skills', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=150, null=True)),
                ('level', models.CharField(max_length=150, null=True)),
                ('Languages', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Connect_Message',
            fields=[
                ('connect_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('connect_message_ts', models.DateTimeField()),
                ('connect_message_text', models.TextField()),
                ('Is_Read', models.BooleanField()),
                ('connect_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.connect')),
                ('connect_message_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.user')),
            ],
        ),
        migrations.AddField(
            model_name='connect',
            name='connected_student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.user'),
        ),
        migrations.AddField(
            model_name='class',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.user'),
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=60, null=True)),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tutor.country')),
            ],
        ),
    ]
